### ISSUE TITLE
Slightly odd interaction with Notes Tabs plugin

### ISSUE THREAD

**Issue by Daeraxa** [ajilderda/joplin-macos-native-theme#26]
If you install the [Notes Tabs plugin](https://github.com/benji300/joplin-note-tabs) which adds a new resizable panel to Joplin, it has a slightly odd interaction with the macOS theme, namely a small section below the tabs and above the title which on the standard theme is invisible but on the macOS theme is bordered by lines. I don't know if this is an interaction just with the custom panels or if the issue is with how Note Tabs works.
Is it related to this comment of yours? https://github.com/ajilderda/joplin-macos-native-theme/issues/5#issuecomment-899497066

Normal view:
![image](https://user-images.githubusercontent.com/58074586/132042310-b507030d-92e5-470d-b44f-93d9a04c74dc.png)

What it looks like under default theme:
![image](https://user-images.githubusercontent.com/58074586/132043203-2f304ee0-f952-4a46-b7a0-4687028e79f3.png)

Putting the tabs frame vertically into the middle of the application doesn't show it to the left or right (taken using macOS theme):
![image](https://user-images.githubusercontent.com/58074586/132043973-0e142eba-2b43-45a5-8f84-80a6b0a65e1d.png)

The element in question is this last div:
```css
<div class="resizableLayoutItem rli-plugin-view-joplin.plugin.note.tabs-note.tabs.panel" style="position: relative; user-select: auto; display: flex; flex-direction: row; width: 550px; height: 40px; min-width: 40px; min-height: 40px; box-sizing: border-box; flex-shrink: 0;">
<div class="sc-fznKkj gCTJhE" style="width: 550px; height: 35px;">
<iframe id="plugin-view-joplin.plugin.note.tabs-note.tabs.panel" width="1105" height="34" src="services/plugins/UserWebviewIndex.html" class="sc-fzoKki hAQvyw">
</iframe></div><span>
<div class="" style="position: absolute; user-select: none; width: 100%; height: 10px; bottom: -5px; left: 0px; cursor: row-resize;"></div>
</span></div>
```

**Comment by ajilderda** [comment]
Hi @Daeraxa, try adding this to your userchrome.css:

```css
.rli-plugin-view-joplin\.plugin\.note\.tabs-note\.tabs\.panel {
  height: 34px !important;
  min-height: 34px !important;
}

.rli-plugin-view-joplin\.plugin\.note\.tabs-note\.tabs\.panel > div > iframe {
  border-bottom: none !important;
}
```

<img width="287" alt="image" src="https://user-images.githubusercontent.com/487182/132459884-3cbe98f4-2f5a-48a8-af14-22ad9ac05fc9.png">
